export const sidebarStyles = {
  container: {
    position: 'fixed' as const,
    top: '0',
    right: '0',
    width: '300px',
    height: '100vh',
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)',
    zIndex: 999999,
    transition: 'transform 0.3s ease-in-out',
    backdropFilter: 'blur(10px)',
    borderRadius: '12px',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px',
    borderBottom: '1px solid rgba(255, 255, 255, 0.3)',
    background: 'linear-gradient(to right, #3b82f6, #6366f1)',
    color: '#fff',
    borderTopLeftRadius: '12px',
    borderTopRightRadius: '12px',
  },
  headerTitle: {
    fontSize: '18px',
    fontWeight: '600',
  },
  closeButton: {
    backgroundColor: 'transparent',
    border: 'none',
    cursor: 'pointer',
    fontSize: '24px',
    color: 'white',
    fontWeight: 'bold',
    transition: 'transform 0.2s ease-in-out',
  },
  content: {
    padding: '16px',
    height: 'calc(100vh - 60px)',
    overflowY: 'auto' as const,
    backgroundColor: 'rgba(247, 250, 252, 0.9)',
    fontSize: '16px',
  },
  toggleButton: {
    position: 'fixed' as const,
    top: '50%',
    transform: 'translateY(-50%)',
    background: 'linear-gradient(to right, #3b82f6, #6366f1)',
    border: 'none',
    borderRadius: '8px 0 0 8px',
    padding: '16px',
    cursor: 'pointer',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.2)',
    zIndex: 999999,
    right: '0',
    transition: 'right 0.3s ease, transform 0.3s ease',
    color: 'white',
    fontSize: '24px',
    fontWeight: 'bold',
  },
  toggleButtonHovered: {
    transform: 'scale(1.1) translateY(-50%)',
  },
  toggleButtonDefault: {
    transform: 'scale(1) translateY(-50%)',
  },
}
