export const contextMenuStyles = {
  container: {
    position: 'fixed' as const,
    zIndex: 9999999,
    backdropFilter: 'blur(10px)',
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    border: '1px solid rgba(255, 255, 255, 0.3)',
    borderRadius: '12px',
    padding: '20px 20px 20px 20px',
    textAlign: 'center' as const,
    transition: 'all 0.3s ease-out',
  },
  button: {
    width: '140px',
    height: '30px',
    padding: '12px 16px',
    borderRadius: '16px',
    fontWeight: '500' as const,
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
    transition:
      'transform 0.2s ease, box-shadow 0.2s ease, background-color 0.2s ease',
    border: '1px solid rgba(255, 255, 255, 0.3)',
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative' as const,
  },
  button1: {
    background: 'linear-gradient(to right, #3b82f6, #6366f1)',
    color: 'white',
  },
  button2: {
    backgroundColor: '#e5e7eb',
    color: '#333',
  },
  spinner: {
    position: 'absolute' as const,
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: '20px',
    height: '20px',
    borderRadius: '50%',
    border: '3px solid rgba(255, 255, 255, 0.3)',
    borderTop: '3px solid white',
    animation: 'spin 0.8s linear infinite',
  },
  contextMenuContainer: (position: { x: number; y: number }) => ({
    position: 'fixed' as const,
    zIndex: 9999999,
    backdropFilter: 'blur(10px)',
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    border: '1px solid rgba(255, 255, 255, 0.3)',
    borderRadius: '12px',
    padding: '20px 20px 20px 20px',
    textAlign: 'center' as const,
    transition: 'all 0.3s ease-out',
    left: `${position.x - 3}px`,
    top: `${position.y - 3}px`,
  }),
}
